### PR TITLE
Add logging and exceptions

### PR DESCRIPTION
**Pull request by ak9999**
Not ready for merging yet, but I just want to get this looked at to see if I'm even doing it right.

### CODE REVIEW

**Comment by akellehe** [comment]
Between lines 73 and 74 as well as 98 and 99 you'll want to put a try/except block. This will let you log what goes wrong in each iteration of the loop; while still moving on to the next ID in the case of an error.

In the `except` portion of the `try`/`except` you can add `logger.exception(e)` to log the exception that's thrown. This will let us find and address it by taking a peek at the logs for the process.

If you use the syntax 
```python
try:
    ... code goes here ...
except Exception, e:
    logger.exception(e)
```

It should work just fine.

**Comment by ak9999** [comment]
I did so but instead of using the syntax you used I went with 

```python
try:
    # code goes here
except Exception as e:
    logger.exception(e)
```

Is that okay?

**Comment by akellehe** [comment]
That's python3 syntax, this project is on python2.7

**Comment by ak9999** [comment]
Works in 2.6 says [PEP 3110](https://www.python.org/dev/peps/pep-3110/#compatibility), but we already have the other syntax all over the project so I'll go with what you wrote.

**Comment by akellehe** [comment]
Looking good, @ak9999! Please pull master and then rebase so you have only one commit in the commits tab above. E.g.

```bash
git checkout master
git pull origin master
git checkout 17-add-error-handling-page-scraper
git rebase -i master
```
If you have merge conflicts you can say 
```bash
git mergetool --tool=vimdiff 
```
or whatever your tool of choice is; then
```bash
git rebase --continue
```
When the dialog comes up with the word "pick" in front of each commit; change all but the first `pick` to `squash` and save and close the file.

Then do 
```bash
git push origin 17-add-error-handling-page-scraper --force
```

**Pull request merged**
