### PR TITLE
Save event

### LINKED ISSUE #29: "Save event" endpoint.
### Summary

When a user sees an event in their feed they should have an option to save it to their personal feed. The scope of this task is to create a POST endpoint to receive that action.

### Description

Create a POST endpoint, `/user/[user_id]/event/[event_id]` that saves the event, `event_id`, to the personal feed of user, `user_id`.

Included in the scope of this ticket is a forward database migration creating a user_event table. The table should have a multi-column index on (`user_id`, `event_id`). The table itself is a [_join table_](https://en.wikipedia.org/wiki/Associative_entity) between the `user` table and the `event` table, creating a many-to-many relationship between the two.

The endpoint should create the entry in the database if it does not exist; and  replace it if it does.

It should return a JSON representation of that record, e.g.

```python
{
    "user_id": 1234,
    "event_id": 5678
}
```

### PR DESCRIPTION
**Pull request by pisoiasul**
For #29 

I have no idea why the commits on Feb 10, 2017 are included :(

How can I remove them ?

I think we need a "date" column in UserEvent, so we can return the events for an user ordered by the date added. Also PK should be event_id and fb_user_id for that table. Will do this in a later commit.

### CODE REVIEW

**Comment by ak9999** [comment]
You gotta squash your commits. Andrew taught me how to do that back [here](https://github.com/akellehe/fb_calendar/pull/28#issuecomment-280874979).

**Comment by pisoiasul** [comment]
No, I want to exclude the first 4 commits from this pull request (and leave only the last one, e90a7cd).

Do you know how can I do that ?

**Comment by ak9999** [comment]
That's what squashing does, it rolls everything into one commit.

**Comment by pisoiasul** [comment]
So I want my pull request to only have the last commit, without the 4 ones in the beginning. They should be excluded.

**Pull request closed without merging**
